Grades endpoint
UTDNebula/nebula-api pull request #155
Opened 2023-02-22 03:05 UTC by kaylambaker

Adds endpoints /grades and /grades/all

/grades endpoint can query using fields from professors, sections, and courses. The query also has parameter representation which can be 'semester', 'section', or 'total'.
The query should be formatted as <collection>.<field>=<query>&representation=<semester|section|total>
example: /grades?professors.last_name=Alagar&representation=section

/grades/all returns data without query and has parameter representation which can be 'semester', 'section', or 'total'

2023-02-23 23:47 UTC, ahshabbir requested changes
I think you also included your parser files. If you want them all in one PR, I would close the grade parser pr

2023-02-23 23:47 UTC, ahshabbir commented on api/server.go
> +	// enable cors
Should we remove this comment or re-enable cors?

2023-02-23 23:47 UTC, ahshabbir commented on api/server.go
> +	port := os.Getenv("PORT")
I think these lines are already executed by LookupEnv. If the environment variable doesn't exist, just set the port.

2023-03-01 18:36 UTC, AdamMcAdamson commented
I believe you updated the server.go erroneously, and included your parser code here too.
The only change there should have been the inclusion of ther line:
```golang
routes.GradesRoute(router)
```

The easiest thing to do would be to create a new branch and add the changes again, this time only including the changes specifically needed for the grades endpoint. (or you could reset this branch, and add the changes, but I don't want you to lose your changes..)

Otherwise, this looks good to me!

2023-03-07 00:15 UTC, closed without merging