Created Primitive Webscraper
UTDNebula/nebula-api pull request #22
Opened 2021-11-09 01:58 UTC by CharlieMahana

2021-11-10 18:39 UTC, WillieCubed requested changes
Some relatively minor changes to make, but nice job on the script.

2021-11-10 18:39 UTC, WillieCubed commented on scraper/scraper.py
> +            'Cookie': 'PTGSESSID={}'.format(self.ptgsessid),
f-strings are cooler.
```suggestion
            'Cookie': f'PTGSESSID={self.ptgsessid}',
```

2021-11-10 18:39 UTC, WillieCubed commented on scraper/scraper.py
> +        # self.logger.info('Sending ReportMonkey query: {0}'.format(query))
Remove commented out code when merging to `develop`. If it's important, add it to another branch.

2021-11-10 18:39 UTC, WillieCubed commented on scraper/scraper.py
> +            r = requests.get('https://coursebook.utdallas.edu')
Could you extract the CourseBook URL to a top-level variable and replace it anywhere it is used?

2021-11-10 18:39 UTC, WillieCubed commented on scraper/scraper.py
> +        downloadURL = 'https://coursebook.utdallas.edu/reportmonkey/cb11-export/{0}/{0}/json'.format(downloadID)
```suggestion
        downloadURL = f'https://coursebook.utdallas.edu/reportmonkey/cb11-export/{downloadID}/{downloadID}/json'
```

2021-11-10 18:39 UTC, WillieCubed commented on scraper/scraper.py
> +    def getSearchSpecifications(self) -> dict:
I'll note this now: stick to PEP 8 (the Python style guide) and use that convention for all of the variable/function/class names: https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles

2021-11-10 18:39 UTC, WillieCubed commented on scraper/scraper.py
> +        # self.logger.info('Sending CourseBook query: {0}'.format(query))
Don't forget to remove this if it isn't necessary for functionality.

2021-11-10 18:39 UTC, WillieCubed commented on scraper/scraper.py
> +    with open('configs/{}'.format(os.environ['CONFIG_FILE']), 'r') as file:
```suggestion
    config_file_name = os.environ['CONFIG_FILE']
    with open(f'configs/{config_file_name}', 'r') as file:
```

2021-11-10 18:39 UTC, WillieCubed commented on scraper/scraper.py
> +    with open('data/{}.json'.format(int(time.time())),'w') as file:
```suggestion
    with open(f'data/{int(time.time()}.json', 'w') as file:
```

2021-11-10 18:39 UTC, WillieCubed commented on scraper/scraper.py
> +                self.logger.info('0 results obtained from query: {0}'.format(query))
```suggestion
                self.logger.info(f'0 results obtained from query: {query}')
```

2021-11-10 18:39 UTC, WillieCubed commented on scraper/scraper.py
> +            query += '&s[]={0}'.format(specifier)
```suggestion
            query += f'&s[]={specifier}'
```
Sidenote for future reference: I'm almost certain there's a library that does something like this, but this is fine.

2021-11-10 18:39 UTC, WillieCubed commented on scraper/scraper.py
> +            self.logger.error('Failed to receive response from query: {0}'.format(query))
```suggestion
            self.logger.error(f'Failed to receive response from query: {query}')
```

2021-11-10 18:39 UTC, WillieCubed commented on scraper/scraper.py
> +            'Cookie': 'PTGSESSID={0}'.format(self.ptgsessid),
```suggestion
            'Cookie': f'PTGSESSID={self.ptgsessid}',
```

2021-11-10 18:39 UTC, WillieCubed commented on scraper/scraper.py
> +            self.logger.error('Failed to parse number of items returned from query: {0}'.format(query))
```suggestion
            self.logger.error(f'Failed to parse number of items returned from query: {query}')
```

2021-11-10 18:39 UTC, WillieCubed commented on scraper/scraper.py
> +            self.logger.error('Failed to parse download link to {0} item(s) from query: {1}'.format(numItems, query))
```suggestion
            self.logger.error(f'Failed to parse download link to {numItems} item(s) from query: {query}')
```

2021-11-10 18:39 UTC, WillieCubed commented on scraper/scraper.py
> +            self.logger.error('Failed to download JSON response for query: {0}'.format(query))
```suggestion
            self.logger.error(f'Failed to download JSON response for query: {query}')
```

2021-11-10 18:39 UTC, WillieCubed commented on scraper/scraper.py
> +            self.logger.error('Failed to convert JSON to dict for query: {0}'.format(query))
```suggestion
            self.logger.error(f'Failed to convert JSON to dict for query: {query}')
```

2021-11-10 19:30 UTC, CharlieMahana commented
I fixed all the issues you mentioned and removed the hardcoded data file in dataToFirestore.py so that the file can be passed into the program through command line arguments

2021-11-10 20:24 UTC, WillieCubed requested changes
Ah, there was a comment that was missed [here](https://github.com/UTDNebula/nebula-api/pull/22/commits/9526714b629d9ccbaa2a7a04f26c1dcae99ac451#r746878065). Additionally, add `.env` to the `.gitignore`.

2021-11-10 20:50 UTC, CharlieMahana commented
I removed the commented code block, finished f-string conversions, and added /scraper/.env to .gitignore. My only concern is that firebase credentials could accidentally be committed to the repository as the credentials file gets a new name every time we generate one. How do we want to solve this problem?

2021-11-10 22:27 UTC, WillieCubed commented
In the project set-up docs, just inform people to rename the file so it has the correct hardcoded name a that is how it is intended to work.

2021-11-11 20:59 UTC, CharlieMahana commented
@WillieCubed my most recent commit should mean everything has been taken care of and we're ready to merge. Let me know if there is anything that I missed.

2021-11-13 05:26 UTC, WillieCubed approved these changes
LGTM!

2021-11-13 05:26 UTC, merged