Add the section aggregate endpoints to the professor
UTDNebula/nebula-api pull request #242
Opened 2024-11-22 04:13 UTC by mikehquan19

This pull request is for task #232. I added the section aggregate endpoints to the professor controllers. I also made the function ```getProfessorQuery(flag string, c *gin.Context)``` which gets the query of the professor depending on the flag that can be used for both ```professorCourse()``` and ```professorSection()```. That way we can reduce redundancy in the code, though I think there's still lots of redundancy in my code. 

Thank you.

2024-11-22 05:57 UTC, jpahm commented
Awesome, thank you! Should be able to review this one much quicker than the last one :)

2025-02-06 19:54 UTC, jpahm commented
Holding onto this until the changes discussed in #241 are made.

2025-02-11 07:42 UTC, mikehquan19 commented
I've implemented pagination on both things of the endpoints. Now the aggregate endpoints will need 2 query params `former_offset` & `latter_offset`.

For example, `course/sections?former_offset=40&latter_offset=60` would mean `course` is skipped to the 40th and `sections` is skipped to the 60th, but the number of `course` & `sections` returned would be limited to 20.

A few notes: 
- `offset` won't work in these endpoints but only the basic endpoints.
- If the user doesn't specify either `former_offset` or `latter_offset`, they would be defaulted to 0. It means that `course/sections` would return the first 20 `sections` from the first 20 `course`.

@jpahm , I have a question. Since I've already got the code working for #243, but since they are really messy just as  we discussed, would you rather I wait until you review and approve this PR and then make a new PR, or commit them directly to this PR?

2025-02-11 20:35 UTC, jpahm commented
Awesome, thank you! I'll review this in detail shortly. Regarding #243, feel free to either wait until I review this or move your commits for #243 to a different branch and make a PR from that.

2025-02-16 23:53 UTC, jpahm requested changes
Overall, looks pretty solid! Just a few suggestions.

2025-02-16 23:53 UTC, jpahm commented on api/configs/setup.go
> +	return formerOffset, latterOffset, limit, err
There's two identical chunks of code here for handling each offset -- perhaps we can trade this out for a loop over the two offset names?

2025-02-16 23:53 UTC, jpahm commented on api/controllers/course.go
> +		err = errors.New("broken endpoint")
I would probably be in favor of using more descriptive error messages than this, but it's okay for now :)

2025-02-16 23:53 UTC, jpahm commented on api/controllers/course.go
> +	log.Logger.Print(len(courses))
```suggestion

```

2025-02-16 23:53 UTC, jpahm commented on api/controllers/course.go
> +	log.Logger.Print(len(courseSections))
```suggestion

```

2025-02-17 00:21 UTC, mikehquan19 commented
Got it! I will improve them in no time.

2025-02-17 00:23 UTC, mikehquan19 commented on api/configs/setup.go
> +	return formerOffset, latterOffset, limit, err
That would make the code better for sure!

2025-02-17 00:24 UTC, mikehquan19 commented on api/controllers/course.go
> +		err = errors.New("broken endpoint")
You are so right! I actually felt weird while I was writing this.

2025-02-17 08:13 UTC, mikehquan19 commented
I've the fixed the issue with the code repetition. Now `getAggregateLimit()` will return a map whose keys are `former_offset`, `latter_offset`, & `limit`, respectively. So aggregate pagination can be based on that. 
I've also written a more descriptive error message. Let me know if it needs any more details.

2025-02-24 00:10 UTC, jpahm approved these changes

2025-02-24 00:11 UTC, merged